<a href="https://colab.research.google.com/github/kanchandhole/Python-assignment/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1.**Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

**Ans:**-NumPy is a fundamental Python library for scientific computing and data analysis, providing highly optimized multi-dimensional arrays and a wide range of mathematical functions, significantly enhancing Python's capabilities for numerical operations by enabling fast, efficient computations on large datasets, especially when compared to standard Python lists, due to its optimized memory allocation and vectorized operations

**Key advantages of NumPy:**

**Performance:**

NumPy arrays are stored in contiguous memory blocks and leverage compiled C code for operations, resulting in significantly faster computations compared to Python lists, particularly for large datasets and complex mathematical calculations.

**Vectorization:**
NumPy allows performing operations on entire arrays at once, eliminating the need for explicit loops and significantly improving performance for element-wise operations.

**Multi-dimensional arrays:**

NumPy's core data structure is the "ndarray" which can represent multi-dimensional arrays (matrices, tensors), making it ideal for handling complex data structures in scientific computing.

**Extensive mathematical functions:**

NumPy provides a rich collection of mathematical functions like trigonometric operations, linear algebra routines, statistical calculations, and more, streamlining complex numerical computations.

**Integration with other libraries:**

NumPy is the foundation for many other scientific Python libraries like SciPy, Pandas, and Matplotlib, enabling seamless integration and data flow between different analysis stages

**How NumPy enhances Python for numerical operations:**

Efficient data manipulation:

By providing optimized array operations, NumPy allows for fast manipulation of large datasets with complex data structures.

Concise code:

Vectorized operations enable writing concise code that performs calculations on entire arrays with minimal loops, improving readability and maintainability.
Advanced mathematical capabilities:
NumPy's extensive mathematical functions provide access to powerful tools for complex calculations like matrix operations, eigenvalue decomposition, and more.

**2.**Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

**ans:**

**np.mean()**
Use to calculate arithmetic mean.

All elements have equal weight

Weight cannot be passed trough the parameter of the given function.

Syntax :

np.mean(arr, axis = None)

where ‘arr’ is the given array.

**np.average()**

Use to calculate the arithmetic mean as well as weighted average.


All elements may or may not have equal weight.


Weight can be passed through the parameter of the given function.

Syntax :

np.mean(arr, axis = None)

where ‘arr’ is the given array.

Syntax :

numpy.average(arr, axis = None, weights = None)

Where ‘arr’ is the given array



**3.**Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

**Ans:**
Using flip() function to Reverse a Numpy array
The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.



In [4]:
import numpy as np

In [5]:
#1D Array:
d1 = np.array([1, 2, 3, 4, 5])

In [7]:
d1

array([1, 2, 3, 4, 5])

In [8]:
np.flip(d1)

array([5, 4, 3, 2, 1])

In [21]:
import random

In [25]:
d2 = np.random.randint(1,3, size=(2,2))

In [26]:
d2

array([[2, 1],
       [1, 1]])

In [27]:
np.flip(d2)

array([[1, 1],
       [1, 2]])

**4.**How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

**Ans:**The list of various types of data types provided by NumPy are given below:

A data type in NumPy is used to specify the type of data stored in a variable. Here is the list of characters available in NumPy to represent data types.

Character

Meaning

b  --Boolean

f --Float

m ---Time Delta

O --Object

U  --Unicode String

i ---Integer

u  --- Unsigned Integer

c --- Complex Float

M --  DateTime

S --- String

V --- A fixed chunk of memory for other types (void)



In [28]:
ar1 = np.array([1,2,3,4])

In [29]:
ar1

array([1, 2, 3, 4])

In [30]:
ar1.dtype

dtype('int64')

**5.**Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

**Ans:**
ndarray((short for N-dimensional array)) is a core object in NumPy. It is a homogeneous array which means it can hold elements of the same data type. It is a multi-dimensional data structure that enables fast and efficient manipulation of large dataset

1D array
arr1 = np.array([1, 2, 3, 4, 5])

2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

3D array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

**differ from list**

 In contrast to lists, NumPy arrays are stored in a single continuous location in memory, making it very easyfor programs to access and manipulate them
 In computer science, this behavior is known as locality of reference
 This is the primary factor that makes NumPy faster than lists. Additionally, it is enhanced to function with modern CPU architectures.


**6.**Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

**Ans:**
NumPy offers faster computation and efficient handling of large datasets compared to traditional Python lists. It provides powerful mathematical functions and operations, simplifying complex tasks. Additionally, NumPy arrays occupy less memory space, enhancing performance in scientific computing and data analysis

**7.**Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

**Ans:**
In NumPy, vstack() is used to vertically stack arrays, meaning it combines them row-wise, while hstack() horizontally stacks arrays, combining them column-wise; essentially,

In [31]:
arr1 = np.array([[1, 2], [3, 4]])

In [35]:
arr1

array([[1, 2],
       [3, 4]])

In [32]:
np.vstack(arr1)

array([[1, 2],
       [3, 4]])

In [33]:
np.hstack(arr1)

array([1, 2, 3, 4])

**8.**Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

**Ans:-**
In NumPy, fliplr() flips an array along its columns (left to right), essentially mirroring it horizontally, while flipud() flips an array along its rows (up to down).

In [34]:
np.fliplr(arr1)

array([[2, 1],
       [4, 3]])

In [36]:
np.flipud(arr1)

array([[3, 4],
       [1, 2]])

**9.**Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

**Ans:**array_split() s plitting into equal or nearly equal sub-arrays or is similar to numpy. split(), but it allows for uneven splitting of arrays. This is useful when the array cannot be evenly divided by the specified number of splits

In [40]:
Arr = np.array([1, 2, 3, 4, 5, 6])

In [41]:
np.split(Arr, 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

**10.**Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

**Ans:**
**Broadcasting** simplifies mathematical operations on arrays with different shapes. It enables NumPy to efficiently apply operations element-wise without explicitly copying or reshaping data.

Example 1 : Broadcasting Array in Single Value and 1D Addition
The code creates a NumPy array arr with values [1, 2, 3]. It adds 1 to each element using broadcasting, resulting in [2, 3, 4], and prints the updated array.

arr = np.array([1, 2, 3])

res = arr + 1  

**Vectorization** is the process of converting an algorithm from operating on a single value at a time to operating on a set of values (vector) at one time. Hence, we can use these techniques to perform operations on Numpy arrays without using loops